# Generated by Django 4.1.5 on 2023-01-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_categoria_post_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
        migrations.DeleteModel(
            name='comentario',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
